Id: Docker.DockerDesktop
Version: 2.3.0.3
Name: DockerDesktop
Publisher: Docker
Homepage: https://www.docker.com/
License: Copyright Docker Inc. 2015
Description: Docker Desktop is an application for MacOS and Windows machines for the building and sharing of containerized applications. Access Docker Desktop and follow the guided onboarding to build your first containerized application in minutes.
Installers: 
    - Arch: x64
      Url: https://desktop.docker.com/win/stable/45519/Docker%20Desktop%20Installer.exe
      InstallerType: exe
      Sha256: FE77C795881420D199352C54F14C3EB6C5ABC2D4D3293A98944FC1ACA320EAE9
